// <auto-generated />
using DataAcessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataAcessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260518154500_SeedMissingVehicleTypeLookupData")]
    partial class SeedMissingVehicleTypeLookupData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
