// <auto-generated />
using System;
using DataAcessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAcessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260512114547_useridteklfiler")]
    partial class useridteklfiler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Entities.BodyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("BodyTypes");
                });

            modelBuilder.Entity("EntityLayer.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("EntityLayer.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("EntityLayer.Entities.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("EntityLayer.Entities.ExpertReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("QuoteRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuoteRequestId");

                    b.ToTable("ExpertReports");
                });

            modelBuilder.Entity("EntityLayer.Entities.FuelType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("FuelTypes");
                });

            modelBuilder.Entity("EntityLayer.Entities.HousingType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("HousingTypes");
                });

            modelBuilder.Entity("EntityLayer.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BuyerReason")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Expenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExpertiseReportContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("ExpertiseReportData")
                        .HasColumnType("bytea");

                    b.Property<string>("ExpertiseReportFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ListingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("NeighborhoodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SoldDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SoldTo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SoldToEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SoldToPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ListingDate");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("Status");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("EntityLayer.Entities.ListingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Base64Data")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("EntityLayer.Entities.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BodyTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("EntityLayer.Entities.Neighborhood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Neighborhoods");
                });

            modelBuilder.Entity("EntityLayer.Entities.NotaryDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("NotaryDocuments");
                });

            modelBuilder.Entity("EntityLayer.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("EntityLayer.Entities.QuoteMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("QuoteRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuoteRequestId");

                    b.ToTable("QuoteMedia");
                });

            modelBuilder.Entity("EntityLayer.Entities.QuoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Damage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Fuel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gear")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Km")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("OfferDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("OfferMaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OfferMinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Plate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Year")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Email");

                    b.HasIndex("IsRead");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("QuoteRequests");
                });

            modelBuilder.Entity("EntityLayer.Entities.RealEstate", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlockNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("BuildingAge")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingCondition")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CeilingHeight")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeedStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("numeric");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FloorAreaRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FrontWidth")
                        .HasColumnType("numeric");

                    b.Property<int?>("GrossArea")
                        .HasColumnType("integer");

                    b.Property<bool?>("HasAirConditioning")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasAlarm")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasBalcony")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasBasement")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasBuiltInKitchen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasCableTv")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasCameraSystem")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasCellar")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasColdStorage")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasCoveredParking")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasElectricityConnection")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasElevator")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasFireSystem")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasFireplace")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGarden")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGenerator")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasInternet")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasLoadingDock")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasMezzanine")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasNaturalGas")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasParking")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasPool")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasSatellite")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasSecurity")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasShowcase")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasShutter")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasSteelDoor")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasStorageRoom")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasTerrace")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasThreePhasePower")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasUnderfloorHeating")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasVideoIntercom")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasWaterSource")
                        .HasColumnType("boolean");

                    b.Property<int?>("HeatingType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HeightLimit")
                        .HasColumnType("numeric");

                    b.Property<Guid>("HousingTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsCreditEligible")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsExchangeable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsFurnished")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRoadAccessible")
                        .HasColumnType("boolean");

                    b.Property<int>("ListingType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MonthlyRent")
                        .HasColumnType("numeric");

                    b.Property<int?>("NetArea")
                        .HasColumnType("integer");

                    b.Property<string>("ParcelNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoomCount")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SheetNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalFloors")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UsageStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("ZoningStatus")
                        .HasColumnType("integer");

                    b.HasKey("ListingId");

                    b.HasIndex("HousingTypeId");

                    b.ToTable("RealEstates");
                });

            modelBuilder.Entity("EntityLayer.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EntityLayer.Entities.SiteContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("SiteContents");
                });

            modelBuilder.Entity("EntityLayer.Entities.TransmissionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("TransmissionTypes");
                });

            modelBuilder.Entity("EntityLayer.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("EmailVerificationCodeExpiry")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EntityLayer.Entities.UserFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId", "ListingId");

                    b.HasIndex("ListingId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("EntityLayer.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BodyTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DamageStatus")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("EngineDisplacement")
                        .HasColumnType("integer");

                    b.Property<int?>("EnginePower")
                        .HasColumnType("integer");

                    b.Property<int?>("FastChargeTime")
                        .HasColumnType("integer");

                    b.Property<Guid>("FuelTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasABS")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAEB")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAUX")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAdaptiveCruiseControl")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAdaptiveLights")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAirConditioning")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAirbag")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAndroidAuto")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasArmoredVehicle")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasArmrest")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAutoDimmingMirror")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBAS")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBlindSpotWarning")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBluetooth")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCarPlay")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCentralLock")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasChildLock")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCooledGlovebox")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCruiseControl")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasDigitalAC")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasDistronic")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasDriverAirbag")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasESP")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasElectricFoldMirrors")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasElectricMirrors")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasElectricSeats")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasElectricWindows")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFabricSeats")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFatigueDetection")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFootTrunkOpener")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFrontCamera")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFrontParkSensor")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFunctionalSteering")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasHardtop")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasHeadUpDisplay")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasHeatedMirrors")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasHeatedSteering")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasHillAssist")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasHydraulicSteering")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasImmobilizer")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasIsofix")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasKeylessEntry")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasLaneAssist")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasLeatherSeats")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMemoryMirrors")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMemorySeats")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasNavigation")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasNightVision")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPanoramicRoof")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasParkAssist")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasParkingSensor")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPassengerAirbag")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasPremiumSound")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRearCamera")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRearEntertainment")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRearParkSensor")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSeatCooling")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSeatHeating")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSmartTrunk")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSpeedLimiter")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasStartStop")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSteeringWheelHeating")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSunroof")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasThirdRowSeats")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTouchScreen")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTowBar")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasTripComputer")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasUSB")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Km")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Range")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TramerAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TramerStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransmissionTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ListingId");

                    b.HasIndex("BodyTypeId");

                    b.HasIndex("BrandId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PackageId");

                    b.HasIndex("TransmissionTypeId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("EntityLayer.Entities.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("EntityLayer.Entities.BodyType", b =>
                {
                    b.HasOne("EntityLayer.Entities.VehicleType", "VehicleType")
                        .WithMany("BodyTypes")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("EntityLayer.Entities.District", b =>
                {
                    b.HasOne("EntityLayer.Entities.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("EntityLayer.Entities.ExpertReport", b =>
                {
                    b.HasOne("EntityLayer.Entities.QuoteRequest", "QuoteRequest")
                        .WithMany("ExpertReports")
                        .HasForeignKey("QuoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("EntityLayer.Entities.Listing", b =>
                {
                    b.HasOne("EntityLayer.Entities.City", "City")
                        .WithMany("Listings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EntityLayer.Entities.District", "District")
                        .WithMany("Listings")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntityLayer.Entities.Neighborhood", "Neighborhood")
                        .WithMany("Listings")
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");

                    b.Navigation("District");

                    b.Navigation("Neighborhood");
                });

            modelBuilder.Entity("EntityLayer.Entities.ListingImage", b =>
                {
                    b.HasOne("EntityLayer.Entities.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("EntityLayer.Entities.Model", b =>
                {
                    b.HasOne("EntityLayer.Entities.BodyType", "BodyType")
                        .WithMany()
                        .HasForeignKey("BodyTypeId");

                    b.HasOne("EntityLayer.Entities.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("EntityLayer.Entities.Neighborhood", b =>
                {
                    b.HasOne("EntityLayer.Entities.District", "District")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("EntityLayer.Entities.NotaryDocument", b =>
                {
                    b.HasOne("EntityLayer.Entities.Listing", "Listing")
                        .WithMany("NotaryDocuments")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("EntityLayer.Entities.Package", b =>
                {
                    b.HasOne("EntityLayer.Entities.Model", "Model")
                        .WithMany("Packages")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("EntityLayer.Entities.QuoteMedia", b =>
                {
                    b.HasOne("EntityLayer.Entities.QuoteRequest", "QuoteRequest")
                        .WithMany("Media")
                        .HasForeignKey("QuoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("EntityLayer.Entities.QuoteRequest", b =>
                {
                    b.HasOne("EntityLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityLayer.Entities.RealEstate", b =>
                {
                    b.HasOne("EntityLayer.Entities.HousingType", "HousingType")
                        .WithMany("RealEstates")
                        .HasForeignKey("HousingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.Listing", "Listing")
                        .WithOne("RealEstate")
                        .HasForeignKey("EntityLayer.Entities.RealEstate", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HousingType");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("EntityLayer.Entities.RefreshToken", b =>
                {
                    b.HasOne("EntityLayer.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityLayer.Entities.UserFavorite", b =>
                {
                    b.HasOne("EntityLayer.Entities.Listing", "Listing")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityLayer.Entities.Vehicle", b =>
                {
                    b.HasOne("EntityLayer.Entities.BodyType", "BodyType")
                        .WithMany("Vehicles")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntityLayer.Entities.Brand", "Brand")
                        .WithMany("Vehicles")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.FuelType", "FuelType")
                        .WithMany("Vehicles")
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.Listing", "Listing")
                        .WithOne("Vehicle")
                        .HasForeignKey("EntityLayer.Entities.Vehicle", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.Model", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.Package", "Package")
                        .WithMany("Vehicles")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntityLayer.Entities.TransmissionType", "TransmissionType")
                        .WithMany("Vehicles")
                        .HasForeignKey("TransmissionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.VehicleType", "VehicleType")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("Brand");

                    b.Navigation("FuelType");

                    b.Navigation("Listing");

                    b.Navigation("Model");

                    b.Navigation("Package");

                    b.Navigation("TransmissionType");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("EntityLayer.Entities.BodyType", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("EntityLayer.Entities.Brand", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("EntityLayer.Entities.City", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("EntityLayer.Entities.District", b =>
                {
                    b.Navigation("Listings");

                    b.Navigation("Neighborhoods");
                });

            modelBuilder.Entity("EntityLayer.Entities.FuelType", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("EntityLayer.Entities.HousingType", b =>
                {
                    b.Navigation("RealEstates");
                });

            modelBuilder.Entity("EntityLayer.Entities.Listing", b =>
                {
                    b.Navigation("FavoritedBy");

                    b.Navigation("Images");

                    b.Navigation("NotaryDocuments");

                    b.Navigation("RealEstate");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("EntityLayer.Entities.Model", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("EntityLayer.Entities.Neighborhood", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("EntityLayer.Entities.Package", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("EntityLayer.Entities.QuoteRequest", b =>
                {
                    b.Navigation("ExpertReports");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("EntityLayer.Entities.TransmissionType", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("EntityLayer.Entities.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("EntityLayer.Entities.VehicleType", b =>
                {
                    b.Navigation("BodyTypes");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
